#!/bin/zsh

# Add to PATH if not a root user
if [ $UID -ne 0 ]; then
  PATH=/s/std/bin:$PATH
fi

# Set PATH
PATH=$PATH:/usr/afsws/bin # AFS SOFTWARE
PATH=$PATH:/opt/SUNWspro/bin # compilers (on Solaris)
PATH=$PATH:/usr/ccs/bin # programming tools (on Solaris)
PATH=$PATH:/usr/ucb # standard programs
PATH=$PATH:/bin # standard programs
PATH=$PATH:/usr/bin # standard programs
PATH=$PATH:/usr/X11R6/bin # X software for linux
PATH=$PATH:/s/handin/bin # handin software
PATH=$PATH:/p/course/cs354-common/public/bin
PATH=$PATH:/s/lab/bin:/s/req/bin:/s/krb5/sbin:/s/lab/pbin
PATH=$PATH:/s/sushi/bin:/s/what/bin
PATH=$PATH:/usr/afsws/bin
PATH=$PATH:/usr/afsws/etci
PATH=$PATH:~/mybin
PATH=$PATH:~/bin
PATH=$PATH:/s/php-5.4.1/bin
PATH=$PATH:~/drupal/drush/

# Removes domain name '.cs.wisc.edu' from hostname
export HOSTNAME=`hostname | sed -e s/\\..\*//`

# Setup alias's
alias ez="easy"
alias e="easy"
alias spi="splat -i"
alias mc="mchange&"
alias lab="ssh walkup-linux"
alias update="sudo apt update && sudo apt upgrade"

