complete -x -c easy -a "(__fish_print_hostnames)"
complete -x -c easy -s h -l help -d "Print help"
complete -x -c easy -s b -d "Backup information for host"
complete -r -c easy -s d -a "(__fish_print_hostnames)" -r -d "Filedist host info"
complete -x -c easy -s i -d "Parts by inventory (C, S, U) numbers"
complete -x -c easy -s k -d "keyrings in a room"
complete -x -c easy -s l -d "Machines in a 'lock' (2360 only)"
complete -x -c easy -o lm -d "Lm status overview"
complete -x -c easy -s m -a "(__fish_print_hostnames)" -d "Soft match mathine (default)"
complete -x -c easy -o mh -a "(__fish_print_hostnames)" -d "Hard match mathine"
complete -x -c easy -s n -d "Info on a user by NetID"
complete -x -c easy -o nx -d "Crosswalk Info on a user by NetID"
complete -x -c easy -s o -d "Parts by ponum"
complete -x -c easy -s p -d "Info on a user by HR Person ID"
complete -x -c easy -o px -d "Crosswalk Info on a user by HR Person ID"
complete -x -c easy -s r -d "Machines in a room"
complete -x -c easy -s s -d "Parts by serial numbers"
complete -x -c easy -s u -d "Info on a user"
complete -x -c easy -o up -d "Info and picture on a user"
